### PR TITLE
move directives, import angular2.dart

### PR DESCRIPTION
**Pull request by kwalrath**
Reflects changes to the stagehand template: https://github.com/google/stagehand/pull/409

### CODE REVIEW

**Comment by Janamou** [comment]
@kwalrath, @filiph - also the firebase-counter-steps repo needs to be updated. Thx

**Comment by kwalrath** [comment]
OK, I'll do that.

**Comment by Janamou** [comment]
Looks good, thx.

Can you please run peanut then @filiph to have the latest version deployed?

**Comment by filiph** [comment]
`gh-pages` updated

**Pull request merged**
